---
title: "Final functions"
author: "Olek Wojcik"
date: "4/22/2021"
output: pdf_document
---
```{r, warning=FALSE}
library(tidyverse)
library(sf)
library(pdxTrees)
library(lwgeom)
```

```{r, warning=FALSE}
set.seed(13)

pdx <- get_pdxTrees_parks() %>%
  sample_n(100)

pdx_sf <- st_as_sf(pdx,
                   coords = c("Longitude", "Latitude"),
                   crs = 4326)

#I don't think we need these helper functions, I used a simpler method below, lmk if I missed something. 
# one_nn_distance <- function(sf_object, one_row, ...){
#   sf_object %>%
#     mutate(distance_temporary_column = as.numeric(st_distance(one_row, sf_object, ...)))%>%
#     #shouldnt make a new column like this
#     filter(distance_temporary_column != 0) %>%
#     #what do we do if multiple points are on the same spot?
#     summarize(m = min(distance_temporary_column)) %>%
#     as.data.frame() %>%
#     dplyr::select(m) %>%
#     as.numeric()
# }
# 
# pdx_one <- slice_head(pdx_sf, n = 1)
# 
# 
# sf_nn_distances <- function(sf_object, ...){
#   sf_object %>%
#     rowwise() %>%
#     mutate(distance = one_nn_distance(sf_object = sf_object,
#                                       one_row = geometry, ...))
#   }
```


##G Function
```{r, fig.height=4,fig.width=5, warning=FALSE}
g_function <- function(sf_object,
                       return_df = FALSE,
                       return_length = 100, ...){

if(class(sf_object) != c("sf", "tbl_df", "tbl", "data.frame")){
  stop("sf_object is class ",
       class(sf_object))
}

if(class(return_df) != "logical"){
  stop("return_df is class ",
       class(return_df))
}

if(class(return_length) != "numeric" & class(return_length) != "integer"){
  stop("return_length is class ",
       class(return_length))
}

  g <- st_distance(sf_object)
gm <- as.matrix(g)
diag(gm) <- NA
distances <- apply(gm, 1, min, na.rm=TRUE)
  max_dist <- max(distances)
  distances_df <- data.frame(distances = distances)
  d <- seq(from = 0, to = max_dist, by = max_dist/return_length)
  props <- d %>%
    map_dbl(.f = function(.){
      #print(distances_df$distances > .)
      mutate(distances_df,
             true = case_when(distances < . ~ 1,
                              distances >= . ~ 0)) %>%
        summarize(prop = mean(true)) %>%
        as.double()
    })
g_df <- data.frame(distance = d,
             prop = props)

if(return_df == TRUE){
  return(g_df)
}

if(return_df == FALSE){
  ggplot(data = g_df,
       mapping = aes(x = distance,
                     y = prop)) +
  geom_line(color = "steelblue") +
  theme_minimal() +
  labs(title = "G-Function")
  
}

}

g <- g_function(pdx_sf )
```


##F Function
```{r, fig.height=4,fig.width=5, warning=FALSE}
set.seed(22)
f_function <- function(sf_object, return_df = FALSE, return_length = 100, ...){

if(class(sf_object) != c("sf", "tbl_df", "tbl", "data.frame")){
  stop("sf_object is class ",
       class(sf_object))
}

if(class(return_df) != "logical"){
  stop("return_df is class ",
       class(return_df))
}

if(class(return_length) != "numeric" & class(return_length) != "integer"){
  stop("return_length is class ",
       class(return_length))
}
  #First generating random points
   bb_studyregion = st_bbox(sf_object) # the study region's bounds
  random_df = tibble(
  x = runif(n = length(sf_object), min = bb_studyregion[1], max = bb_studyregion[3]),
  y = runif(n = length(sf_object), min = bb_studyregion[2], max = bb_studyregion[4])
  )
  random_points = random_df %>% 
  st_as_sf(coords = c("x", "y")) %>% # set coordinates
  st_set_crs(st_crs(sf_object)) # set geographic CRS 
 #prepping for the F-function formula
  dt <- st_distance(random_points, sf_object$geometry)
  dm <- as.matrix(dt)
  distances <- apply(dm, 1, min, na.rm=TRUE)
  max_dist <- max(distances)
  distances_df <- data.frame(distances = distances)
  d <- seq(from = 0, to = max_dist, by = max_dist/return_length)
  props <- d %>%
    map_dbl(.f = function(.){
      #print(distances_df$distances > .)
      mutate(distances_df,
             true = case_when(distances < . ~ 1,
                              distances >= . ~ 0)) %>%
        summarize(prop = mean(true)) %>%
        as.double()
    })
 f_df <- data.frame(distance = d,
             prop = props)
if(return_df == TRUE){
  return(f_df)
}

 if(return_df == FALSE){
   ggplot(data = f_df,
       mapping = aes(x = distance,
                     y = prop)) +
  geom_line(color = "steelblue") +
  theme_minimal() +
  labs(title = "F-Function")
 }

}
f <- f_function(pdx_sf)
```


##K Function
```{r, fig.height=4,fig.width=5, warning=FALSE}
library(geosphere)
k_function <- function(sf_object, return_df = FALSE, return_length = 100, ...){

if(class(sf_object) != c("sf", "tbl_df", "tbl", "data.frame")){
  stop("sf_object is class ",
       class(sf_object))
}

if(class(return_df) != "logical"){
  stop("return_df is class ",
       class(return_df))
}

if(class(return_length) != "numeric" & class(return_length) != "integer"){
  stop("return_length is class ",
       class(return_length))
}
  
pol <-  st_as_sfc(st_bbox(sf_object))
sfarea <- as.numeric(st_area(pol))
sfdens <- as.numeric(sfarea/nrow(sf_object))

#distance
d <- distm(st_coordinates(sf_object),st_coordinates(sf_object), fun=distHaversine)
#Applying formula from class
dist <- seq(1, 25000, return_length)
Kd <- sapply(dist, function(x) sum(d < x)) # takes a while
Kd <- Kd / (length(Kd) * sfdens)
K_df <- data.frame(distance = dist, Kd=Kd)

if(return_df == TRUE){
  return(K_df)
}

if(return_df == FALSE){
  ggplot(data = K_df,
       mapping = aes(x = distance,
                     y = Kd)) +
  geom_line(color = "steelblue") +
  theme_minimal() +
  labs(title = "K-Function") 
  
}

}
k <- k_function(pdx_sf)
```


```{r, warning=FALSE}
library(spatstat)
library(gridExtra)
pts.owin <- owin(c(-122.76421,-122.48729), c(45.46413,45.64891))
coords <- sf::st_coordinates(pdx_sf)
pdx_ppp <- ppp(x = coords[,1], y = coords[,2],window =  pts.owin)
G <- Gest(pdx_ppp)
F <- Fest(pdx_ppp)
K <- Kest(pdx_ppp)
```

#Comparing our plots vs. spatstat plots
```{r, fig.height=5, fig.width=12, warning=FALSE}
grid.arrange(g,f,k, ncol=3)
par(mfrow=c(1,3))
plot(G$km, type="l")
plot(F$km, type='l')
plot(K$iso, type='l')
```



```{r, warning=FALSE}
#trash experimental functions
one_nn <- function(one_row, sf_object){
  sf_object %>%
    mutate(distance_temporary_column = as.numeric(st_distance(one_row, sf_object)))%>%
    #shouldnt make a new column like this
    filter(distance_temporary_column != 0) %>%
    #what do we do if multiple points are on the same spot?
    filter(distance_temporary_column == min(distance_temporary_column)) %>%
    select(-distance_temporary_column)
}

sf_nn <- function(sf_object){
  sf_object %>%
    rowwise() %>%
    map(.f = function(.){
      #one_geom <- st_transform(., crs = 4326)
      one_nn(., sf_object)
    })
}
```


